### PR TITLE
Update Bazel 1.2.1 → 3.0.0.

### PR DESCRIPTION
**Pull request by arturdryomov**
Changes:

* [Bazel 2.0](https://blog.bazel.build/2019/12/19/bazel-2.0.html)
* [Bazel 2.1](https://blog.bazel.build/2020/02/06/bazel-2.1.html)
* [Bazel 2.2](https://blog.bazel.build/2020/03/03/bazel-2-2.html)
* [Bazel 3.0](https://blog.bazel.build/2020/03/31/bazel-3.0.html)

A big version bump but doesn’t look like a lot of breaking changes for rules.

### CODE REVIEW

**Comment by arturdryomov** [comment]
@artem-zinnatullin, @Kernald, 🏓

**Comment by Kernald** [comment]
Did you pinpoint exactly why the changes were required? I didn't see anything relevant in the changelogs, I'm curious.

**Comment by arturdryomov** [comment]
@Kernald, do you mean changes in analysis tests? Not sure TBH. These paths were always implementation-specific so I’m not surprised internal Bazel paths were changed eventually.

**Comment by Kernald** [comment]
Fair enough!

**Pull request merged**
