### PR TITLE
Switch to Bazelisk

### PR DESCRIPTION
**Pull request by arturdryomov**
I’ve been looking for a good way to set up a local environment for a specific Bazel version and seems like Bazelisk is the way to go. The Homebrew version might be ahead / behind the required version and managing binaries manually feels... barbaric. Felt like it makes sense to apply this to CI as well.

### CODE REVIEW

**Comment by arturdryomov** [comment]
@artem-zinnatullin, WDYT?

**Comment by Kernald** [comment]
While it makes sense for local development, I'm not sure what's the added value on CI? The CI system would end up downloading both Bazelisk and Bazel, when it previously downloaded a specific Bazel version anyway.

**Comment by arturdryomov** [comment]
Executing the same thing on CI makes sure that the local environment will behave the same (and vice versa). Also it provides a single source of truth for the current Bazel version via the `.bazelversion`.

**Comment by Kernald** [comment]
By definition for rules, other users are going to depend on you, and you don't control the way Bazel is invoked. I'm not sure trying to have a similar environment in CI and for your local development is a goal worth pursuing. Having a single source of truth of the current Bazel version is a fair point - assuming that everyone uses Bazelisk.

**Comment by arturdryomov** [comment]
From my POV everyone should use Bazelisk, otherwise it’s like using Gradle without a Gradle wrapper. Of course I’m very much a noob in this. Actually I’ve created bazelbuild/bazel#10348 about this — quiet so far.

**Comment by artem-zinnatullin** [comment]
We have custom bazelw at Lyft, but for OSS I agree that Bazelisk is the way to go

**Pull request merged**
